name: Build Android APK

# GitHub ကို Code တင်လိုက်တာနဲ့ Auto အလုပ်လုပ်မယ်
on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # ၁။ Code တွေကို ဆွဲယူမယ်
    - name: Checkout source
      uses: actions/checkout@v3

    # ၂။ Buildozer သုံးပြီး APK ထုတ်မယ်
    - name: Build with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      id: buildozer
      with:
        command: buildozer android debug
        buildozer_version: master

    # ၃။ ရလာတဲ့ APK ဖိုင်ကို GitHub မှာ Download ဆွဲလို့ရအောင် တင်ပေးမယ်
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: KoCLay-App-APK
        path: bin/*.apk
